### ISSUE TITLE
Unnecessary constants

### ISSUE THREAD

**Issue by aleksey-ios-dev** [ZombieWang/SURVEYS#15]
```
let DequeueCardCell = "CardCell"
let DequeuePagerCell = "PagerCell"
let ToDetailVC = "ToDetailVC"
```

This could be done by using NSStringFromClass. Don't create separate files for constants, they tend to become garbage collectors.

**Comment by yentzu-wang** [comment]
Thank you for your good advice. I found some solutions and improvements for these kinds of situation.
