### ISSUE TITLE
Spaghetti code in MainVC, SRP violation

### ISSUE THREAD

**Issue by aleksey-ios-dev** [ZombieWang/SURVEYS#18]
First, view controller is something that controls a view. But `reloadData()` function does almost all the application logic: fetches remote data, parses, displays alerts and activity indicators, reloads the collection view. This is called spaghetti code which is pretty hard to maintain.

https://en.wikipedia.org/wiki/Single_responsibility_principle

**Comment by yentzu-wang** [comment]
Created a new data model to solve this problem.
